# Generated by Django 4.1.2 on 2022-11-25 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1_little', models.CharField(max_length=150, null=True, verbose_name='Tittle 1 Little')),
                ('title_1', models.CharField(max_length=150, null=True, verbose_name='Title 1')),
                ('title_2', models.CharField(max_length=150, null=True, verbose_name='Title 2')),
            ],
            options={
                'verbose_name': 'About Title',
                'verbose_name_plural': 'About Titles',
            },
        ),
        migrations.CreateModel(
            name='AboutHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Header')),
                ('content', models.TextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'About Content',
                'verbose_name_plural': 'About Contents',
            },
        ),
        migrations.CreateModel(
            name='AboutHeader_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Header')),
                ('content', models.TextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'About Content 2',
                'verbose_name_plural': 'About Contents 2',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('surname', models.CharField(max_length=25, null=True, verbose_name='Surname')),
                ('number', models.CharField(max_length=20, null=True, verbose_name='Number')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
                ('text', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='Logo')),
                ('header_text', models.TextField()),
                ('instagram', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'General Settings',
                'verbose_name_plural': 'General Settings',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('image', models.ImageField(upload_to='Instructors')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='Images', verbose_name='Add Image')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('draft', models.BooleanField(default=False, verbose_name='Show')),
                ('problem', models.TextField(blank=True, null=True)),
                ('solution_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='Images', verbose_name='Add Image')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='blog.product')),
            ],
        ),
    ]
