# Generated by Django 4.1.2 on 2022-10-31 12:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_1', ckeditor.fields.RichTextField(verbose_name='Text 1')),
                ('text_2', ckeditor.fields.RichTextField(verbose_name='Text 1')),
                ('text_3', ckeditor.fields.RichTextField(verbose_name='Text 1')),
            ],
        ),
    ]
