# Generated by Django 4.1.2 on 2022-11-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_footer_3_generalsettings_facebook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='aboutheader',
            options={'verbose_name': 'About Header', 'verbose_name_plural': 'About Header'},
        ),
        migrations.AlterModelOptions(
            name='aboutheader_2',
            options={'verbose_name': 'About Header 2', 'verbose_name_plural': 'About Header 2'},
        ),
        migrations.AddField(
            model_name='aboutheader',
            name='little_header',
            field=models.TextField(null=True),
        ),
    ]
