# Generated by Django 4.1.2 on 2022-10-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
                ('text', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
