# Generated by Django 4.1.2 on 2022-11-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_solution_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='show',
            field=models.BooleanField(default=False, verbose_name='Show'),
        ),
    ]
