# Generated by Django 4.1.2 on 2022-11-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_product_turn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Galeries', 'verbose_name_plural': 'Galeries'},
        ),
        migrations.AlterField(
            model_name='about',
            name='title_1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Title 1'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_1_little',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tittle 1 Little'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Title 2'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
