# Generated by Django 4.1.2 on 2022-11-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_about_options_alter_aboutheader_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About Title', 'verbose_name_plural': 'About Titles'},
        ),
        migrations.AlterModelOptions(
            name='aboutheader',
            options={'verbose_name': 'About Content', 'verbose_name_plural': 'About Contents'},
        ),
        migrations.AlterModelOptions(
            name='aboutheader_2',
            options={'verbose_name': 'About Content 2', 'verbose_name_plural': 'About Contents 2'},
        ),
        migrations.RemoveField(
            model_name='aboutheader',
            name='little_header',
        ),
        migrations.AddField(
            model_name='about',
            name='title_1_little',
            field=models.CharField(max_length=150, null=True, verbose_name='Tittle 1 Little'),
        ),
    ]
