# Generated by Django 4.1.2 on 2022-11-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_about_options_alter_aboutheader_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='problem',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='solution_text',
            field=models.TextField(null=True),
        ),
    ]
