# Generated by Django 3.2 on 2022-12-28 11:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_product_options_alter_about_title_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title_1',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Title 1'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_1_little',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tittle 1 Little'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_2',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Title 2'),
        ),
        migrations.AlterField(
            model_name='aboutheader',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='aboutheader',
            name='header',
            field=ckeditor.fields.RichTextField(max_length=100, verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='aboutheader_2',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='aboutheader_2',
            name='header',
            field=ckeditor.fields.RichTextField(max_length=100, verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='header_text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='problem',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='solution_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
