# Generated by Django 4.1.2 on 2022-11-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_product_problem_product_solution_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='image_4',
        ),
        migrations.AddField(
            model_name='solution',
            name='image',
            field=models.ImageField(null=True, upload_to='Images', verbose_name='Add Image'),
        ),
    ]
