# Generated by Django 3.2 on 2023-01-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20221228_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='social_link',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='surname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
