# Generated by Django 4.1.2 on 2022-11-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_solution_image_1_remove_solution_image_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalsettings',
            options={'verbose_name': 'General Settings', 'verbose_name_plural': 'General Settings'},
        ),
    ]
