# Generated by Django 3.2 on 2023-01-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20230130_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='social_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
