# Generated by Django 3.2 on 2023-03-15 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20230130_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='Ravan_pp')),
                ('positon', models.CharField(blank=True, max_length=100, null=True)),
                ('mail', models.CharField(blank=True, max_length=500, null=True)),
                ('adress', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=500, null=True)),
                ('github', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook', models.CharField(blank=True, max_length=500, null=True)),
                ('page_title', models.CharField(max_length=300)),
                ('title_about', models.CharField(max_length=300)),
                ('experience_year', models.PositiveIntegerField(default=1)),
                ('projects_count', models.PositiveIntegerField(default=1)),
                ('about_title', models.CharField(max_length=300)),
                ('about_main', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=200)),
                ('count', models.PositiveIntegerField(default=0)),
                ('user_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialization', to='blog.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='Skills')),
                ('user_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='blog.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=300)),
                ('start_year', models.CharField(max_length=100)),
                ('end_year', models.CharField(max_length=100)),
                ('user_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='blog.portfolio')),
            ],
        ),
    ]
