# Generated by Django 3.2 on 2023-03-18 04:39

from django.db import migrations, models
import django.db.models.deletion
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_education_portfolio_skills_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('main_title', models.CharField(max_length=200)),
                ('main_image', django_base64field.fields.Base64Field(blank=True, default='', max_length=900000, null=True)),
                ('url', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='blog.portfolio')),
            ],
        ),
    ]
