# Generated by Django 4.1.2 on 2022-11-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.CharField(max_length=20, null=True, verbose_name='Number'),
        ),
        migrations.AddField(
            model_name='contact',
            name='surname',
            field=models.CharField(max_length=25, null=True, verbose_name='Surname'),
        ),
    ]
