# Generated by Django 4.1.2 on 2022-11-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_contact_number_contact_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Header')),
                ('content', models.TextField(verbose_name='Content')),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='text_1',
            field=models.TextField(verbose_name='Text 1'),
        ),
        migrations.AlterField(
            model_name='about',
            name='text_2',
            field=models.TextField(verbose_name='Text 2'),
        ),
        migrations.AlterField(
            model_name='about',
            name='text_3',
            field=models.TextField(verbose_name='Text 3'),
        ),
    ]
