# Generated by Django 4.1.2 on 2022-11-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_aboutheader_alter_about_text_1_alter_about_text_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='text_1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='text_2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='text_3',
        ),
        migrations.AddField(
            model_name='about',
            name='title_1',
            field=models.CharField(max_length=150, null=True, verbose_name='Title 1'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_2',
            field=models.CharField(max_length=150, null=True, verbose_name='Title 2'),
        ),
    ]
