# Generated by Django 3.2 on 2023-03-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20230318_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_link',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
