# Generated by Django 4.1.2 on 2022-11-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_about_text_1_remove_about_text_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHeader_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Header')),
                ('content', models.TextField(verbose_name='Content')),
            ],
        ),
    ]
