# Generated by Django 3.2 on 2023-03-23 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_project_video_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='twitter',
            new_name='whatsapp',
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=300)),
                ('start_year', models.CharField(max_length=100)),
                ('end_year', models.CharField(max_length=100)),
                ('user_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='blog.portfolio')),
            ],
        ),
    ]
