# Generated by Django 3.2 on 2023-03-23 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20230323_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Certificate')),
                ('text', models.TextField()),
                ('user_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='blog.portfolio')),
            ],
        ),
    ]
