# Generated by Django 4.1.2 on 2022-11-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='Logo')),
                ('header_text', models.TextField()),
                ('footer_1', models.CharField(max_length=50)),
                ('footer_2', models.CharField(max_length=50)),
            ],
        ),
    ]
