# Generated by Django 3.2 on 2023-03-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='experience_year',
            field=models.FloatField(default=1),
        ),
    ]
