# Generated by Django 4.1.2 on 2022-11-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_rename_image_product_image_1_product_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='footer_3',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
