# Generated by Django 3.2 on 2023-03-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_portfolio_experience_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
