# Generated by Django 4.1.2 on 2022-11-15 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_generalsettings_footer_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='Images', verbose_name='Add Image')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='Images', verbose_name='Add Image')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='Images', verbose_name='Add Image')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='Images', verbose_name='Add Image')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='blog.product')),
            ],
        ),
    ]
