# Generated by Django 3.2 on 2023-03-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_certificate_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='telegram',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
