# Generated by Django 4.1.2 on 2022-11-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_solution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='event',
            new_name='porduct',
        ),
    ]
