# Generated by Django 3.2 on 2023-03-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_portfolio_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='video_link',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
