# Generated by Django 4.1.2 on 2022-11-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_rename_event_solution_porduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='porduct',
            new_name='product',
        ),
    ]
