# Generated by Django 4.1.2 on 2022-11-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_rename_porduct_solution_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_4',
        ),
    ]
