# Generated by Django 4.1.2 on 2022-11-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_images_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image',
            new_name='document',
        ),
    ]
