# Generated by Django 4.1.2 on 2022-11-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_rename_image_images_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='Images', verbose_name='Add Image'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
